<template>
  <button
    class="
      flex
      items-center
      px-6
      py-2
      text-base
      text-center
      font-poppings         
      font-semibold
      align-middle
      text-white
      transition
      rounded-md
      bg-azul
      hover:bg-gray-700
      active:bg-gray-900
      disabled:opacity-25
      mx-auto
    "
  >
    <slot></slot>
  </button>
</template>