<template>
  <button
    class="
      inline-flex
      items-center
      px-6
      py-2
      text-xs
      font-medium
      text-white
      transition
      rounded-md
      bg-azul
      hover:bg-gray-700
      active:bg-gray-900
      disabled:opacity-25
      mx-auto
    "
  >
    <slot></slot>
  </button>
</template>